### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by cissemy** [oliversturm/devextreme-query-mongodb#1]
Hi
How can i make CRUD call ?

**Comment by oliversturm** [comment]
The functionality of this module only covers querying (i.e. the R part of CRUD), because there is lots of extra logic required to translate the options passed by the DevExtreme data layer, run a set of queries (depending on the options - in some cases, like grouping with summaries, there are quite a lot of them) and generate the result set in the format that is, again, understood by the DevExtreme data layer.
In contrast, creating new records, editing or deleting them, are very straight-forward implementations that are not specific to the DevExtreme library. I suggest checking out the MongoDB docs that show these techniques in detail (and also show how easy it is!): https://docs.mongodb.com/getting-started/node/insert/ 

Finally, I will post follow-ups to my blog post (https://community.devexpress.com/blogs/oliver/archive/2017/02/09/querying-a-mongodb-collection-using-devextreme-data-store-load-parameters.aspx), hopefully within the next few weeks, that will show an example of creating a full-blown REST service to interface with DevExtreme and MongoDB (and much other stuff).
