### ISSUE TITLE
replaceId is called even if _id is already a string in mongo

### ISSUE THREAD

**Issue by JD2k** [oliversturm/devextreme-query-mongodb#35]
Error message:

Exception while invoking method 'analysisTemplates/get' TypeError: item._id.toHexString is not a function
at replaceId (webpack:///./node_modules/devextreme-query-mongodb/dist/utils.js?:8:56)

Should be replaced with something like

`return item._id ? { ...item, _id: item._id.toHexString ? item._id.toHexString() : item._id } : item;`

By the way, thanks for this package. Saved me a lot of work.

**Comment by oliversturm** [comment]
I realize this is a very old issue, but I blame GitHub for not notifying me. Sorry about that.

What is your `item._id`? I believe in my tests the assumption was valid that it would have this function - but it's been a while. 

**Edit:** I guess your `item._id` is a string, based on the subject. In that case I think the option mentioned below is your best choice. I'll close this, please feel free to reopen if necessary.

Also, perhaps you should pass `replaceIds: false` with your [processing options](https://github.com/oliversturm/devextreme-query-mongodb/wiki/QueryAPI#processing-option-replaceids)? That would be more efficient because the projection is not even attempted.
