### ISSUE TITLE
Inner object in record how to specify schema type

### ISSUE THREAD

**Issue by jonathanalberghini** [oliversturm/devextreme-query-mongodb#36]
If I have a record that contains 
an inner object mySubsMsg.enabled which is a bool.
How do you specify that in the schema?
Neither of these work.

```function getQueryOptions (req) {
  return getOptions(req.query, {
    'mySubsMsg.enabled': 'bool',
    mytype: 'int'
  })

function getQueryOptions (req) {
  return getOptions(req.query, {
    mySubsMsg: {
      enabled: 'bool'
    },
    mytype: 'int'
  })
}

```

**Comment by jonathanalberghini** [comment]
I was able to get it to work 

```{
    'messages.mySubsMsg.enabled': 'bool',
    mytype: 'int'
  }```

Is this the correct way to do it???

I had a typo is there any Devextreme sample dealing with grids and inner object editing?

**Comment by oliversturm** [comment]
I realize this is a very old issue, but I blame GitHub for not notifying me. Sorry about that.

I believe the syntax you found should be okay from the perspective of schema handling on the level of this library. I'm not aware of a DevExtreme sample that illustrates editing of nested objects - they're mostly more SQL centric. However, you should contact DevExpress support if you haven't done so yet, to make sure. If I find time I'll conduct some tests myself because your question has made me curious!

Closing for now, please reopen as necessary.
