### ISSUE TITLE
Lookup fields and inner Arrays

### ISSUE THREAD

**Issue by jonathanalberghini** [oliversturm/devextreme-query-mongodb#39]
I have a look up shield and in the parent collection it contains an array of ids. I am using reacrt/angular devex[press grid.
Is there anyway you have a sample of how to do that lookup field that display  a comma delimited list. But when you edit it it would pop up on multi select which will allow you to select the name instead of the ID from the child table. And then how are you would be able to save it back as the value underneath which would be a comma delimited list that would need to be turned into an array.

I have tried their tech-support and they told me to reach out to you but I am willing to pay for this I can send you a simple little sample and I would pay for the code.

**Comment by oliversturm** [comment]
Hi Jonathan,

This is certainly an interesting use case, but I have no ready-made sample for it. When I find some time I'd look into this out of curiosity, but meanwhile I'm afraid I don't think this is directly related to my MongoDB query interface project. 

I'm surprised that DevExpress support pointed you here! Can you let me have an issue number for the DevExpress Support Center, so I can follow up on this and see why you were referred here in the first place? It seems to me that your question is much more related to the components than the specific database interface you use. On the other hand perhaps I'm misunderstanding the problem -- if you can elaborate so that the connection to the storage driver becomes more obvious, please do so.

Thanks
Oliver

**Comment by jonathanalberghini** [comment]
Ticket T1116785  Visible to All Users  Urgent
https://supportcenter.devexpress.com/ticket/details/t1116785/display-and-edit-with-grid-a-json-object-with-an-inner-array-that-has-keys-to-another

**Comment by jonathanalberghini** [comment]
I have 2 scenarios I will detail with sample data just give me a day to put together.
Thanks so much!

**Comment by jonathanalberghini** [comment]
I am new to devexpress js 
Scenario 1
sample data 
{
    "_id" : ObjectId("5f60df19f1ae1d21d1b43f15"),
    "slug" : "billing",
    "content" : "<p><strong>Why is “{{BRAND-BILLING-DESCRIPTOR}}” .</p>",
    "wordpressSiteName" : [
        "LG",
        "PB",
        "AK",
        "OT",
        "CR",
        "BR",
        "JC",
        "RE",
        "WM"
    ]
}

I have a list of site and want to be able to edit this record in the data grid. My though is I would have to return the data to the grid as not an array bit comma separated list of site abbr's. And the on edit somehow l select the correct entries in a multiselect dropdown and let them edit and then turn back into comma separated list for display and then turn back. into an array when data is sent back to mongo  api.

Scenario 2
Data 
Collection 1 
{
"_id" : ObjectId**("63209447b2ce02af2b7d6cde"),**
"wpKey" : NumberLong**(400000117157),**
"wordpressId" : NumberInt**(117157),**
"code" : "welcome-to-the-crypto-corner",
"title" : "Welcome to the Crypto Corner",
"description" : "Welcome to the Crypto Corner",
"wordpressSiteName" : "PB",
"label" : "Welcome to the Crypto Corner",
"pubCode" : [
ObjectId**("62663ba1ba50b4a3e394c936"),**
ObjectId**("62663ba1ba50b4a3e394ce3f"),**
ObjectId**("62663ba1ba50b4a3e394ca4c"),**
ObjectId**("62663ba1ba50b4a3e394c8ca"),**
ObjectId**("62663ba1ba50b4a3e394c96f"),**
ObjectId**("62663ba1ba50b4a3e394cba4"),**
ObjectId**("62663ba1ba50b4a3e394cd53"),**
ObjectId**("62663ba1ba50b4a3e394c9b9")**
],
"ctaContent" : "",
"displayOrder" : NumberInt**(1)**
}

the pubcode relate to another collection 
Collection 2

{
    "_id" : ObjectId("62663ba1ba50b4a3e394c9b9"),
    "wpKey" : NumberLong(100000116186),
    "wordpressId" : NumberInt(116186),
    "code" : "lgm",
    "title" : "LGM",
    "description" : "Mega ",
    "wordpressSiteName" : "LG",
    "authcode" : "LGM"
}

So in the grid while editing collection  1 I would like to have a look up set up to bring back the title from collection to and display it as a comma delimited list.  And then when I added it I would have a list of all of the values from collection 2 to select from and the multi select will allow you to add and remove them and then when the data is saved I would need to turn it back into an array so I could save it to mongo. I cannot find any samples anywhere that deal with inner arrays when editing a record. With all the hooks on the grid that you can tie into I am fairly sure that this is possible I'm just trying to get a couple samples. If you wanted to make some extra money I am desperate and I would gladly pay for the two samples. If I wasn't in such a time crunch I would probably just dig through the code until I figured it out. But between being new to Dev express and my time constraints I am just trying to get a sample that I can start from.

**Comment by oliversturm** [comment]
Well… I’m afraid this has nothing to do with this project — it covers data querying only, it does not offer an opinion or any technical implementation that has to do with editing data or posting back to your server. 

I see that [your DevExpress ticket](https://supportcenter.devexpress.com/ticket/details/t1116785/display-and-edit-with-grid-a-json-object-with-an-inner-array-that-has-keys-to-another) points to [this issue in this repo](https://github.com/oliversturm/devextreme-query-mongodb/issues/1), which also states that *devextreme-query-mongodb* is not responsible for editing.

Generally, this is the approach to create a MongoDB based app that uses DevExpress controls:

* Figure out your data storage structure
* Create data services with your own API that allows you CRUD (or whatever other structure) read/write access to your data
* Consider using *devextreme-query-mongodb* to simplify the step of attaching the convenient client-side feature set of DevExtreme UI controls to your data backend — it can translate the DevExtreme control data layers and their UI-based option sets into MongoDB compatible queries, thus saving you time
* Add and attach code to the client-side controls to transmit post data (or more generally, *commands*) to your existing APIs to account for any write operations back to your system.

I see that there’s a chance here for us to provide a sample, and I will put this in my schedule. Unfortunately I can’t promise a specific timeline right now, and I’m afraid I will close this issue because the topic is really out of scope for the *devextreme-query-mongodb* project.

For future purposes, it would be good to have your sample scenario, but I’m afraid it’s badly readable due to the formatting. If you’d like, I’d appreciate correctly formatted source snippets, there’s a chance a sample could be built around them later.
